- name: print variables
  hosts: web
  vars: #play level variables, apllicable for all tasks
    NAME: "Hari"
    DEPT: "Devops"
    DURATION: "3 yrs"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "{{NAME}} has been working in {{DEPT}} for {{DURATION}}"

  - name: print variables
    vars:
      DEPT: "Ansible"
    ansible.builtin.debug:
      msg: "{{NAME}} has been working in {{DEPT}} for {{DURATION}}"
