- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: NAME
    prompt: Please provide name
    private: false
  - name: DEPT
    prompt: Please provide department
    private: false
  - name: DURATION
    prompt: Please provide duration
    private: false
  tasks:
  - name: variables from prompt
    ansible.builtin.debug:
      msg: "{{NAME}} has been working in {{DEPT}} for {{DURATION}}"